# Generated by Django 4.0.2 on 2022-03-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('image_bank', models.ImageField(blank=True, upload_to='donate/bank')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stk', models.CharField(blank=True, max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='donate/qrcode')),
                ('name', models.CharField(default='HOANG VAN GIOI', max_length=150)),
                ('link', models.URLField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.bank')),
            ],
        ),
    ]
