# Generated by Django 4.0.2 on 2022-03-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
