# Generated by Django 4.0.2 on 2022-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamabout',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamabout',
            name='url_fb',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
