# Generated by Django 4.0.2 on 2022-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_teamabout_position_teamabout_url_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
