# Generated by Django 4.0.2 on 2022-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_about_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamabout',
            old_name='url_fb',
            new_name='url_facebook',
        ),
        migrations.AddField(
            model_name='teamabout',
            name='url_github',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamabout',
            name='url_instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
